# Generated by Django 6.1.1 on 2026-09-10 02:45

import multisite.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multisite", "0004_alter_alias_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="is_canonical",
            field=models.BooleanField(
                default=None,
                editable=False,
                help_text="Does this domain name match the one in site?",
                null=True,
                validators=[multisite.models.validators.validate_true_or_none],
                verbose_name="is canonical?",
            ),
        ),
    ]
