# Generated by Django 4.2.11 on 2024-03-27 04:14

from django.db import migrations

import django_multisite2.models.managers


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_multisite2",
            "0003_alter_alias_options_alter_alias_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="alias",
            managers=[
                ("objects", django_multisite2.models.managers.AliasManager()),
                (
                    "canonical",
                    django_multisite2.models.managers.CanonicalAliasManager(),
                ),
                (
                    "aliases",
                    django_multisite2.models.managers.NotCanonicalAliasManager(),
                ),
            ],
        ),
    ]
